import { useState } from "react";
import { Modal } from "antd";
import Head from "next/head";
import { useRouter } from "next/router";

export default function History() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const router = useRouter();

  const showModal = () => {
    setIsModalOpen(true);
  };
  const handleOk = () => {
    setIsModalOpen(false);
  };
  const handleCancel = () => {
    setIsModalOpen(false);
  };
  const handleChat = (name) => {
    router.push({
      pathname: "/chat",
      query: { patientName: name },
    });
  };

  return (
    <>
      <Head>
        <title>NEXTGEN Doctors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="flex flex-col items-center justify-start bg-[#00444d] text-white text:lg sm:text-3xl w-full min-h-screen gap-5 p-4">
          {[1, 2, 3, 4, 5].map((index) => {
            return (
              <div
                key={index}
                className="w-full rounded-xl bg-white py-4 text-black flex flex-col items-center justify-start font-semibold"
              >
                <div className="w-full px-4">
                  <h1>
                    <b>Patient Name:</b> <span>John Doe</span>
                  </h1>
                  <h1>
                    <b>Appointment Date</b> <span>May 02, 2023.</span>
                  </h1>
                  <h1>
                    <b>Appointment Time:</b> <span>1pm</span>
                  </h1>
                  <div className="w-full flex flex-row gap-2">
                    <button
                      className="w-1/2 bg-[#00444d] text-white font-bold rounded-md h-10"
                      onClick={showModal}
                    >
                      view report
                    </button>
                    <button
                      className="w-1/2 bg-[#00444d] text-white font-bold rounded-md h-10"
                      onClick={() => handleChat("John Doe")}
                    >
                      chat
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
          <Modal
            title="Patient Complaint"
            open={isModalOpen}
            footer={null}
            onOk={handleOk}
            onCancel={handleCancel}
            centered
          >
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
          </Modal>
        </section>
      </main>
    </>
  );
}
