import Head from "next/head";
import Link from "next/link";
import Splash from "@/components/Splash-Screen/Splash";

export default function Home() {
  return (
    <>
      <Head>
        <title>NEXTGEN Doctors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Splash />
        <section className="flex flex-col items-start justify-center bgimg bg-right sm:bg-center w-full min-h-screen gap-12 xl:gap-10 lg:pt-8">
          <div className="flex flex-col justify-center items-center sm:items-start w-full px-4 text-black dark:text-white sm:px-20 blurdiv">
            <h1 className="w-full text-4xl text-center sm:text-left">
              Get instant access to patient records <br /> with our QR code
              scanning system.
            </h1>
            <br />
            <p className="w-full max-w-lg text-xl text-center sm:text-left">
              Welcome to <b className="text-[#00444d]">NextGen Doctors</b> where
              you can give medical care from anywhere you are to those who need
              you.
            </p>
            <div className="flex sm:flex-row flex-col items-start justify-center w-fit gap-4 mt-6 sm:mt-10">
              <Link
                href="/scan"
                className="p-2 w-64 bg-[#2a9988] hover:bg-[#1C665B] duration-500 rounded-md text-white text-xl max-w-[250px] text-center"
              >
                Scan QR
              </Link>
              <Link
                href="/history"
                className="p-2 w-64 border border-[#2a9988] bg-[#2a9988] hover:bg-[#1C665B] dark:bg-black dark:hover:bg-[#1C665B] duration-500 rounded-md text-white text-xl max-w-[250px] text-center"
              >
                Consultations
              </Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
